import '@/styles/globals.scss';
import { Inter } from 'next/font/google';
import { Header, Footer } from '@/components';
import classNames from 'classnames';
import styles from './layout.module.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Graph QL App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body className={classNames(inter.className, styles.body)}>
        <Header></Header>
        <main className={styles.main}>{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
