import '@/styles/globals.scss';
import { Inter } from 'next/font/google';
import { Providers } from '@/redux/provider';
import { Footer } from '@/components';
import classNames from 'classnames';
import styles from './layout.module.scss';
import { Header } from '@/components/layout/Header/Header';

const inter = Inter({ subsets: ['latin'], weight: '400' });

export const metadata = {
  title: 'Graph QL App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: string };
}): JSX.Element {
  return (
    <html lang={lang}>
      <body className={classNames(inter.className, styles.body)}>
        <Providers>
          <Header />
          <main className={styles.main}>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
